# Facilita la ejecución de los programas utilizando la consola de Ubuntu

pc:
	@ python3 dvs128_timeslib_tracking_pc.py
	
pynq:
	@ sudo python3 dvs128_timeslib_tracking_pynq.py

eventsToImage:
	@ sudo python3 dvs128_ip_EventsToImage.py

umbral:
	@ sudo python3 dvs128_ip_Umbral.py

clean:
	@ sudo rm "frame_"*
